update to river 0.4

diff --git a/.local/bin/kwmblocks b/.local/bin/kwmblocks
--- a/.local/bin/kwmblocks
+++ b/.local/bin/kwmblocks
@@ -2,6 +2,18 @@
 
 sec=0
 proc_num=$(nproc)
+fifo_file="/tmp/kwm-status.fifo"
+
+if [ -n "$1" ]; then
+    fifo_file="$1"
+fi
+
+if [ ! -p "$fifo_file" ]; then
+    if ! mkfifo "$fifo_file"; then
+        echo "create FIFO file $fifo_file failed"
+        exit 1
+    fi
+fi
 
 update_time () {
     local icon=""
@@ -153,9 +165,10 @@ trap	"update_brightness;display"	"RTMIN+2"   # -36 .local/bin/bright
 
 display () {
     local space=" "         # ` `(U+2009) is the Thin Space
-    local delimiter_home="["
-    local delimiter_end="]"
-    local separator="]["
+    local delimiter_color="^#EED49FFF"
+    local delimiter_home="$delimiter_color[^#!"
+    local delimiter_end="$delimiter_color]^#!"
+    local separator="$delimiter_color][^#!"
     printf "%s" "${delimiter_home}${memory}${space}${cpu}${space}${temperature}${separator}${wifi}${space}${ethernet}${separator}${brightness}${space}${microphone}${space}${volume}${separator}${battery}${space}${bluetooth}${separator}${time}${delimiter_end}"
 }
 
@@ -179,4 +192,4 @@ do
         sec=$((sec + 1))
     }
     sleep 1 & wait
-done
+done > $fifo_file
